version: '1'
services:
    microservice:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
      - spring.datasource.url=jdbc:oracle:thin:@a8qye6ta3deuch8t_tp?TNS_ADMIN=/app/wallet
      - spring.datasource.username=DSY2201_S4
      - spring.datasource.password=ActForm.S4_BDY
      - TNS_ADMIN=/app/wallet    # extra (adem√°s del JAVA_TOOL_OPTIONS del Dockerfile)
      volumes:
      - "C:/Ingenieria/DSY2201/Exp3_S8/Exp3_S8/Wallet:/app/wallet:ro"    
      restart: always